version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres-estudo
    restart: always
    environment:
      POSTGRES_USER: al3ncar
      POSTGRES_PASSWORD: postgresSQL
      POSTGRES_DB: estudo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
